keys:
  - &users:
      - &pl age1kgjfu9qecyhmy4cvh45zmqj62m4s4nafcfklpqfym9gcmlara47qu4km45
  - &hosts:
    - &Pascal-X240 age15jen6m0gv49z9y6x9540ngcs65zhfjjlrgnv4esj75csvsh3pv6qnk8lct
    - &Pascal-Server age1msa45y2dvvgl8rhkw9c5s434c5uhmyjps3aulgnkvsm3yulqupmscy8uy0
creation_rules:
  - path_regex:  secrets.yaml$
    key_groups:
    - age:
      - *pl
      - *Pascal-X240
      - *Pascal-Server

